import json

from qwen_agent.agents import Assistant
from qwen_agent.tools.base import BaseTool, register_tool


@register_tool('get_current_temperature')
class TemperatureReader(BaseTool):
    # The `description` tells the agent the functionality of this tool.
    description = 'Get the current temperature at the user\'s location.'
    name = 'get_current_temperature'
    # The `parameters` tell the agent what input parameters the tool has.
    parameters = [{
        'name': 'unit',
        'type': "string", "enum": ["celsius", "fahrenheit"],
        'description': 'The unit of measurement.',
        'default': 'celsius',
        'required': True
    }]

    def call(self, params: str, **kwargs) -> int:
        # `params` are the arguments generated by the LLM agent.
        unit = json.loads(params)['unit']
        if unit == 'celsius':
            return 20
        else:
            return 70


llm_cfg = {
    'model': 'qwen2.5:3b',
    'model_server': 'http://localhost:11434/v1',
    'api_key': 'EMPTY',

    'generate_cfg': {
        'top_p': 0.8,
        'temperature': 0.7,
        'max_tokens': 2048,
    }
}

system_instruction = '''You are a helpful assistant. Use tools to complete the user prompt when necessary.'''
bot = Assistant(
    llm=llm_cfg,
    system_message=system_instruction,
    function_list=[TemperatureReader()]
)

messages = [{'role': 'user', 'content': "Tell me the current temperature in celsius."}]
responses = ''
for responses in bot.run(messages=messages):
    pass
print(responses)
